name: Publish

on:
  push:
    tags:
      - 'debian/*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Install dependencies
        run: |
          sudo apt install python3-pip git-buildpackage debmake debhelper-compat dh-python python3-all
      - name: Build package
        run: gbp buildpackage --git-pristine-tar --git-ignore-branch
      - name: Test package
        run: |
          sudo apt install -y ../*.deb
          which openvpn-ldap-auth
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          file_glob: true
          file: ../*.deb
